
#define SCREEN_HEIGHT 25
#define SCREEN_WIDTH 80
#define SCREEN_SIZE SCREEN_HEIGHT*SCREEN_WIDTH

char menu[SCREEN_HEIGHT][SCREEN_WIDTH] = 
{
    "--------------------------------------------------------------------------------",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "   DDDDD                  kk                    KK  KK                          ",
    "   DD  DD   oooo  nn nnn  kk  kk   eee  yy   yy KK KK   oooo  nn nnn   gggggg   ",
    "   DD   DD oo  oo nnn  nn kkkkk  ee   e yy   yy KKKK   oo  oo nnn  nn gg   gg   ",
    "   DD   DD oo  oo nn   nn kk kk  eeeee   yyyyyy KK KK  oo  oo nn   nn ggggggg   ",
    "   DDDDDD   oooo  nn   nn kk  kk  eeeee      yy KK  KK  oooo  nn   nn      gg   ",
    "                                          yyyyy                         ggggg   ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "--------------------------------------------------------------------------------",
};

char map_1[SCREEN_HEIGHT][SCREEN_WIDTH] = 
{
    "                                                                                ",
    "--------------------------------------------------------------------------------",
    "                                                                                ",
    "                                   ______                                       ",
    "                                   zZzZzZ                                       ",
    "                                                                                ",
    "                                                                                ",
    "           ___________________________________________                          ",
    "           zZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZz                          ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                          _________________________________                     ",
    "                          ZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZ                     ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                     _________________________________                          ",
    "                     zZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZz                          ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                     ______________________________________                     ",
    "                     zZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZ                     ",
    "--------------------------------------------------------------------------------",
};

char ladders_level_1[SCREEN_HEIGHT][SCREEN_WIDTH] = 
{
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                |_|                                             ",
    "                                |_|    |_|                                      ",
    "                                |_|    |_|                                      ",
    "                                |_|    |_|                                      ",
    "                                |_|    |_|                                      ",
    "                                        |_|        |_|                          ",
    "                                        |_|        |_|                          ",
    "                                        |_|        |_|                          ",
    "                                        |_|        |_|                          ",
    "                                        |_|        |_|                          ",
    "                          |_|     |_|                                           ",
    "                          |_|     |_|                                           ",
    "                          |_|     |_|                                           ",
    "                          |_|     |_|                                           ",
    "                          |_|     |_|                                           ",
    "                                                  |_|                           ",
    "                                                  |_|                           ",
    "                                                  |_|                           ",
    "                                                  |_|                           ",
    "                                                  |_|                           ",
    "                                                                                ",
    "                                                                                ",
};

char ladders_level_2[SCREEN_HEIGHT][SCREEN_WIDTH] = 
{
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                       |_|                                      ",
    "                                       |_|                                      ",
    "                                       |_|                                      ",
    "                                       |_|                                      ",
    "                               |_|                                              ",
    "                               |_|                                              ",
    "                               |_|                                              ",
    "                               |_|                                              ",
    "                               |_|                                              ",
    "                                  |_|              |_|                          ",
    "                                  |_|              |_|                          ",
    "                                  |_|              |_|                          ",
    "                                  |_|              |_|                          ",
    "                                  |_|              |_|                          ",
    "                           |_|                                                  ",
    "                           |_|                                                  ",
    "                           |_|                                                  ",
    "                           |_|                                                  ",
    "                           |_|                                                  ",
    "                                                                                ",
    "                                                                                ",
};

char ladders_level_3[SCREEN_HEIGHT][SCREEN_WIDTH] = 
{
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                       |_|                                      ",
    "                                       |_|                                      ",
    "                                       |_|                                      ",
    "                                       |_|                                      ",
    "                               |_|                                              ",
    "                               |_|                                              ",
    "                               |_|                                              ",
    "                               |_|                                              ",
    "                               |_|                                              ",
    "                                                   |_|                          ",
    "                                                   |_|                          ",
    "                                                   |_|                          ",
    "                                                   |_|                          ",
    "                                                   |_|                          ",
    "                           |_|                                                  ",
    "                           |_|                                                  ",
    "                           |_|                                                  ",
    "                           |_|                                                  ",
    "                           |_|                                                  ",
    "                                                                                ",
    "                                                                                ",
};

